---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: payment-validation
  labels:
    run: payment-validation
spec:
  replicas: 1
  selector:
    matchLabels:
      run: payment-validation
  template:
    metadata:
      creationTimestamp:
      labels:
        run: payment-validation
    spec:
      containers:
      - name: payment-validation
        image: payment-validation:v1
        ports:
        - containerPort: 3002
          protocol: TCP
        imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: payment-validation
  labels:
    run: payment-validation
spec:
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
    nodePort: 30773
  selector:
    run: payment-validation
  type: LoadBalancer
