---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: money-transfer
  labels:
    run: money-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      run: money-transfer
  template:
    metadata:
      creationTimestamp:
      labels:
        run: money-transfer
    spec:
      containers:
      - name: money-transfer
        image: money-transfer:v1
        ports:
        - containerPort: 8081
          protocol: TCP
        imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: money-transfer
  labels:
    run: money-transfer
spec:
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 31982
  selector:
    run: money-transfer
  type: LoadBalancer
