---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: payment-execution
  labels:
    run: payment-execution
spec:
  replicas: 1
  selector:
    matchLabels:
      run: payment-execution
  template:
    metadata:
      creationTimestamp:
      labels:
        run: payment-execution
    spec:
      containers:
      - name: payment-execution
        image: payment-execution:v1
        ports:
        - containerPort: 8082
          protocol: TCP
        imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: payment-execution
  labels:
    run: payment-execution
spec:
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    nodePort: 31472
  selector:
    run: payment-execution
  type: LoadBalancer
